### ISSUE TITLE
BenchUtiliz enables KernelArmExportPMUUser

### ISSUE THREAD

**Issue by axel-h** [SEL4PROJ/global-components#12]
When the global component are used, the `components/BenchUtiliz/CMakeLists.txt` enables `KernelArmExportPMUUser` unconditionally. This causes `check_export_pmu()` in the kernel  init to access the cp15 register `DBGSDER`, which triggers a undefined instruction abort on the zynq7000 QEMU platform. 

Is there a way to only do this when the CAmkES component BenchUtiliz is really instanciated in a system? This wont solve the root issue of the crash, but at least it will not cause the system to crash when no BenchUtiliz component is used.

**Comment by kent-mcleod** [comment]
Ah. What should be happening is that the component tests if the feature is enabled and then causes a compiler error if it isn't. And then any application using the component is required to enable the feature if it uses the component.

**Comment by axel-h** [comment]
That sounds more reasonable and seems much easier to implement than figuring out if this component is really instanciated and then enable this setting.
